version: '3.9'
services:
  suricata:
    build: 
      context: ./Dockerfiles
      dockerfile: Suricata.Dockerfile
    networks:
      internal_network:
        ipv4_address: 172.20.10.2
        aliases:
          - eth0
      external_network:
        ipv4_address: 192.168.100.2
        aliases:
          - eth1
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./logs:/var/log/suricata:rw
      
    #suricata -i eth0 -k none -l /var/log/suricataa

#  logstash:
#    image: logstash:8.5.3
#    networks:
#      internal_network:
#        ipv4_address: 172.20.10.3
#    volumes:
#      - ../logs:/var/log/suricata:ro
#    depends_on:
#      - suricata

  target:
    build: 
      context: ./Dockerfiles
      dockerfile: Target.Dockerfile    
    networks:
      internal_network:
        ipv4_address: 172.20.10.10
    cap_add:
      - NET_ADMIN
#    depends_on:
#      - logstash

  attacker:
    build: 
      context: ./Dockerfiles
      dockerfile: Attacker.Dockerfile
    networks:
      external_network:
        ipv4_address: 192.168.100.10
    cap_add:
      - NET_ADMIN
    environment:
      - TARGET_IP=172.20.10.10
#    depends_on:
#      - target

networks:
  internal_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.10.0/24
          ip_range: 172.20.10.0/24
  external_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
          ip_range: 192.168.100.0/24
