version: '3.9'
services:
  suricata:
    build: 
      context: ./Dockerfiles
      dockerfile: Suricata.Dockerfile
    networks:
      internal_network:
        ipv4_address: 172.20.10.2
        aliases:
          - eth0
    volumes:
      - ./logs:/var/log/suricata:rw
      - ./Dockerfiles/files/suricata.yaml:/etc/suricata/suricata.yaml:ro
      - ./Dockerfiles/files/telegraf.config:/etc/telegraf/telegraf.config:ro
      - ./Dockerfiles/scripts/suricata.sh:/script/suricata.sh
      - /mnt/e/pcaps/all/:/pcap/
    depends_on:
      questdb:
        condition: service_healthy

  questdb:
    build: 
      context: ./Dockerfiles
      dockerfile: Questdb.Dockerfile
    networks:
      internal_network:
        ipv4_address: 172.20.10.10
    ports:
      - 8812
      - 9000:9000
      - 9009
    volumes:
      - /mnt/e/memoire_db:/root/.questdb/
    healthcheck:
      test: ["CMD", "curl", "-v", "http://127.0.0.1:9003"]
      interval: 10s
      timeout: 5s
      retries: 10

  grafana:
    image: grafana/grafana:9.3.2
    networks:
      internal_network:
        ipv4_address: 172.20.10.20
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_PATHS_DATA=/var/lib/grafana
    volumes:
      - ./grafana:/var/lib/grafana:rwx
    depends_on:
      questdb:
        condition: service_healthy

networks:
  internal_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.10.0/24
          ip_range: 172.20.10.0/24